name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: subosito/flutter-action@v1
        with:
            flutter-version: '3.22.2'
      - name: Download Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --release --web-renderer=canvaskit

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit 
          baseHref: /fluttercon_2024/